### PR TITLE
New attempt at getting v0.3.0 onto `conga-forge` 

### PR DESCRIPTION
**Pull request by ks905383**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ks905383** [comment]
Hey @raybellwaves it looks like I'm back to not having write access to the feedstock for some reason - could you approve this PR? Should be working now. 

Thanks!

**Comment by ks905383** [comment]
@conda-forge-admin, please update team

**Comment by raybellwaves** [comment]
weird I see you are a maintainer in the recipe

**Review by raybellwaves — APPROVED** [review]

**Comment by raybellwaves** [comment]
I can merge if you like. Can look at permissions after that

**Comment by ks905383** [comment]
Please do! Might contact conda forge admins on this (I tried to bump the bot above, but it might take some time)

**Comment by ks905383** [comment]
Thanks @raybellwaves - also it looks like I'm now added to the write access list.

**Pull request merged**
