### PR TITLE
update to v0.2.6

### PR DESCRIPTION
**Pull request by ks905383**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin please rerender

### CODE REVIEW

**Comment by raybellwaves** [comment]
@ks905383 you want to be a maintainer of this repo?

**Comment by ks905383** [comment]
Happy to be! I originally stopped by here to figure out why 0.2.6 wasn't being updated in conda - looks like there's some issue in `xesmf`'s dependencies relating to `numba` (which is odd, because `numba` is on Conda-forge?). Have you run into something like this before?

**Comment by raybellwaves** [comment]
> Happy to be! I originally stopped by here to figure out why 0.2.6 wasn't being updated in conda - looks like there's some issue in `xesmf`'s dependencies relating to `numba` (which is odd, because `numba` is on Conda-forge?). Have you run into something like this before?

Numba isn't getting picked up with the requirements. May have to add it in the receipe.

**Comment by ks905383** [comment]
Yeah, looks like adding numba to the recipe explicitly fixed it

**Comment by raybellwaves** [comment]
@ks905383 you have permission to merge now

**Comment by ks905383** [comment]
hm, oddly enough I'm still getting a "only those with write access can merge pull requests" message

**Comment by raybellwaves** [comment]
> hm, oddly enough I'm still getting a "only those with write access can merge pull requests" message

hmm. Maybe on the next PR as it was added recently.

**Pull request merged**
